import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { collectOfficialProfilePackages, SHELL_PACKAGE_ROOT } from "../src/official-packages.ts";

const list = await collectOfficialProfilePackages();

const content = `/**
 * GENERATED by scripts/gen-official-packages.ts — do not edit by hand.
 * 桌面组合加载的官方插件包：dsh-base 与 dsh-web-app bundle 的 cordis.patch.yml
 * 非禁用条目引用的 @deepseek-ai/* 包（子路径行归到包名）。上游升级后重跑：
 *   pnpm --filter @morlay/dsh-desktop-shell run gen:official-packages
 */
export const OFFICIAL_PROFILE_PACKAGES: readonly string[] = [
${list.map((name) => `  ${JSON.stringify(name)},`).join("\n")}
];
`;
await writeFile(join(SHELL_PACKAGE_ROOT, "src", "official-packages.generated.ts"), content);
console.log(`official packages: wrote ${String(list.length)} packages`);
