name: release

on:
  push:
    branches:
      - main
      - next

permissions:
  contents: read
  packages: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d postgres" --health-interval 2s --health-timeout 2s --health-retries 15
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v5

      - run: just vendor prepare
      - run: just dep
      - run: just build
      - run: just lint
      - run: just test
        env:
          TEST_PG_URL: postgres://postgres:postgres@localhost:5432/postgres
      - run: just build

  publish:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v5
      - run: just vendor prepare
      - run: just dep

      - name: Login to GitHub Packages
        run: pnpm exec tsx scripts/login.mts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: just publish
